### ISSUE TITLE
PCA doesn't work anymore on MNIST with correlation matrix that supports missing values

### ISSUE THREAD

**Issue by HanKruiger** [vmware/hillview#151]
Netty gives an error saying that we exceed the framesize limit. I think it's because `CorrMatrix` uses too much memory. I'll look into this, there'll likely be some memory optimizations possible.

**Comment by HanKruiger** [comment]
```
io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Frame size 9869635 exceeds maximum: 4194304. 
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lalithsuresh** [comment]
Can you see if 81420731f4b5cc2ecacaae7329751276cb5a548c fixes the issue?

**Comment by HanKruiger** [comment]
Sadly, I still get the same error message.

**Comment by lalithsuresh** [comment]
Ah, for some reason I thought you were seeing that error at the server side. Try again with 3856d606718a8c00212b40a7dcf1b9ed6ab6a493.

**Comment by HanKruiger** [comment]
It works now. Thanks 👍

**Comment by mbudiu-vmw** [comment]
So can we close this issue?

**Comment by HanKruiger** [comment]
Yes, #152 closed fixed this!
