### ISSUE TITLE
Frontend not loading correctly

### ISSUE THREAD

**Issue by dn0sar** [vmware/hillview#307]
The `load' bar menu is not shown in the web browser.

When opening the hillview frontend webpage I get the following errors in the browser console:

```
bundle.js Failed to load resource: the server responded with a status of 404 ()
Uncaught TypeError: Cannot read property 'createLoadMenu' of undefined
    at loaded ((index):33)
    at onload ((index):37)
```

The bundle.js file is **not** present in hillview/web/target/web-1.0-SNAPSHOT, however  `mvn package` completes successfully.

System info:
OS: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
java version “1.8.0_161"
node --version -> v8.10.0

Note: This error makes hillview unusable in my system.

**Comment by mbudiu-vmw** [comment]
If bundle.js is not present it means that nothing will work, there is no javascript code at all.
The javascript code is created by webpack, which runs as part of `mvn package`. 
Can you post the output of your `mvn package` execution?
Please note that we have moved to a new version of webpack a few months back, please make sure you are using the right version. In principle the build system should take care of that too.

**Comment by dn0sar** [comment]
This is the output of `mvn package`:

> 
> [INFO] Scanning for projects...
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building web 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
> ~/hillview/web/src/main/webapp ~/hillview/web
> Installing npm packages
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> up to date in 3.886s
> Running webpack command in src/main/webapp
> The CLI moved into a separate package: webpack-cli.
> Please install 'webpack-cli' in addition to webpack itself to use the CLI.
> -> When using npm: npm install webpack-cli -D
> -> When using yarn: yarn add webpack-cli -D
> ~/hillview/web
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ web ---
> [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
> [INFO] skip non existing resourceDirectory ~/hillview/web/src/main/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ web ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ web ---
> [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
> [INFO] skip non existing resourceDirectory ~/hillview/web/src/test/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ web ---
> [INFO] No sources to compile
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.17:test (default-test) @ web ---
> [INFO] No tests to run.
> [INFO] 
> [INFO] --- maven-war-plugin:2.2:war (default-war) @ web ---
> [INFO] Packaging webapp
> [INFO] Assembling webapp [web] in [~/hillview/web/target/web-1.0-SNAPSHOT]
> [INFO] Processing war project
> [INFO] Copying webapp resources [~/hillview/web/src/main/webapp]
> [INFO] Webapp assembled in [1563 msecs]
> [INFO] Building war: ~/hillview/web/target/web-1.0-SNAPSHOT.war
> [INFO] WEB-INF/web.xml already added, skipping
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 14.588 s
> [INFO] Finished at: 2018-03-12T18:47:00+01:00
> [INFO] Final Memory: 25M/1493M
> [INFO] ------------------------------------------------------------------------

**Comment by mbudiu-vmw** [comment]
It looks like you don't have webpack at all. This is a bug, because maven should fail in this case.
In the meantime, can you make sure you have webpack 3.x installed?
https://github.com/webpack/webpack
I don't understand why npm didn't do this for you.

**Comment by mbudiu-vmw** [comment]
I hope I have fixed this one; `mvn install` should now try to install webpack if not available; If webpack does not exist the build should fail.

**Comment by dn0sar** [comment]
With your fix now at least I get an error when compiling.
However, I did not manage to get webpack (or when I manage to install webpack, webpack-cli was not installed). I tried on ubuntu 14.04 LTS, 16.04 LTS, and 17.10. For the latter I also tried on a clean install of Ubuntu, but the result is the same, webpack does not get installed by npm and the `mvn package` fails.

Steps to reproduce:
- Install ubuntu 17.10
- Install git
- Install oracle java
- Clone hillview
- cd hillview/bin
- ./install-dependences.sh
- ./rebuild.sh

Is it maybe an issue with the version number you require? Do you know a ubuntu version in which all hillview's dependencies are known to install without problems?

Thanks.

**Comment by mbudiu-vmw** [comment]
webpack-cli is not needed
what is the error you get?
Maybe I need to run the webpack installation command as sudo

**Comment by dn0sar** [comment]
This is the error I get when webpack is installed:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
~/hillview/web/src/main/webapp ~/hillview/web
Installing npm packages
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.932s
Running webpack command in src/main/webapp
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.977 s
[INFO] Finished at: 2018-03-15T17:12:47+01:00
[INFO] Final Memory: 29M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (Webpack bundle generation) on project web: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mbudiu-vmw** [comment]
The problem is that you don't have webpack installed.
What happens if you just try to install it manually?
`sudo npm install -h webpack`

**Comment by mbudiu-vmw** [comment]
This is why I hate javascript so much.
These guys cannot even keep backwards compatibility.
New versions of webpack work differently from old versions.

**Comment by mbudiu-vmw** [comment]
Ok, apparently webpack 4.0 is not backwards compatible with webpack 3.x.
Try this instead:
`sudo npm install -g webpack@3.6.0`
I will update the install script.

**Comment by dn0sar** [comment]
I still get the same error:

```
sudo npm install -g webpack@3.6.0
/usr/bin/webpack -> /usr/lib/node_modules/webpack/bin/webpack.js

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/lib/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/webpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@3.6.0
added 96 packages, removed 51 packages and updated 10 packages in 10.952s
root@tildem:~/hillview/web# mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
~/hillview/web/src/main/webapp ~/hillview/web
Installing npm packages
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.921s
Running webpack command in src/main/webapp
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.914 s
[INFO] Finished at: 2018-03-15T17:25:28+01:00
[INFO] Final Memory: 29M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (Webpack bundle generation) on project web: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mbudiu-vmw** [comment]
I think you have another version of webpack somewhere installed.
Try `which webpack`. It should be in `/usr/local/bin` probably.

**Comment by mbudiu-vmw** [comment]
You have to use webpack 3.6.0. 
`webpack --version`

**Comment by dn0sar** [comment]
I had to delete the folder of webpack manually and then install again 3.6.0.

I still get an error, but at least is different:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
~/hillview/web/src/main/webapp ~/hillview/web
Installing npm packages
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.903s
Running webpack command in src/main/webapp
Hash: eb57cb64a693a41932f0
Version: webpack 3.11.0
Time: 684ms
          Asset     Size  Chunks             Chunk Names
    ./bundle.js  2.89 kB       0  [emitted]  main
./bundle.js.map  2.46 kB       0  [emitted]  main
   [0] ./hillview.ts 385 bytes {0} [built] [failed] [1 error]

ERROR in ./hillview.ts
Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
    at successfulTypeScriptInstance (/usr/local/lib/node_modules/ts-loader/dist/instances.js:147:28)
    at Object.getTypeScriptInstance (/usr/local/lib/node_modules/ts-loader/dist/instances.js:48:12)
    at Object.loader (/usr/local/lib/node_modules/ts-loader/dist/index.js:16:41)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.999 s
[INFO] Finished at: 2018-03-16T14:53:36+01:00
[INFO] Final Memory: 29M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (Webpack bundle generation) on project web: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Any idea of what can be causing this one?

**Comment by mbudiu-vmw** [comment]
Wonderful. Looks like a version mismatch for ts-loader. what is your version?

**Comment by dn0sar** [comment]
I apparently had some 4.x version of it, I was trying to downgrade to 3.5.0 but I'm not familiar with npm and it took me a while to figure out how to uninstall (somehow `npm uninstall ts-loader` was keeping the 4.x version around..)

It compiled now, however I had to change the path of the loader of `hillview/web/src/main/webapp/webpack.config.js` to `/usr/lib/node_modules/ts-loader`.

I have npm 5.6.0, is that path the new default path for modules?

**Comment by mbudiu-vmw** [comment]
Npm can be configured locally:
https://stackoverflow.com/questions/5926672/where-does-npm-install-packages

I will try to fix the install scripts to use a specific version of ts-loader
