### ISSUE TITLE
"Create column" complains about missing column even when it exists.

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/hillview#382]
We ran into this when processing some traces. I'm able to reproduce this on the flights dataset with a function "row['Col1'] + row['Col2']".

ca43051a-f244-4a99-87ea-76e0cd9c0bce.createColumn() java.lang.Exception: java.lang.RuntimeException: java.lang.RuntimeException: No column named ActualElapsedTime at org.hillview.dataset.LocalDataSet.lambda$map$1(LocalDataSet.java:118) Caused by: java.lang.RuntimeException: java.lang.RuntimeException: No column named ActualElapsedTime at org.hillview.maps.CreateColumnJSMap.createColumn(CreateColumnJSMap.java:139) at org.hillview.maps.AppendColumnMap.apply(AppendColumnMap.java:54) at org.hillview.maps.AppendColumnMap.apply(AppendColumnMap.java:28) at org.hillview.dataset.LocalDataSet.lambda$map$1(LocalDataSet.java:113) ... 12 more Caused by: java.lang.RuntimeException: No column named ActualElapsedTime at org.hillview.table.rows.VirtualRowSnapshot.getColumnChecked(VirtualRowSnapshot.java:175) at org.hillview.table.rows.JSVirtualRowSnapshot.get(JSVirtualRowSnapshot.java:50) at jdk.nashorn.internal.scripts.Script$Recompilation$25$18A$\^eval\_.map(:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:659)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.hillview.maps.CreateColumnJSMap.createColumn(CreateColumnJSMap.java:93)
	... 15 more

**Comment by mbudiu-vmw** [comment]
You need to select all columns that will be used to compute the resulting value.
The error message is not very good...
