### ISSUE TITLE
Couldn't able build web project

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#497]
root@hillview-root:~/shiva/hillview/bin# ./rebuild.sh
~/shiva/hillview/web ~/shiva/hillview/bin
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ web ---
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
/root/shiva/hillview/web/scripts/webpack.sh: line 12: ./node_modules/.bin/webpack: No such file or directory
~/shiva/hillview/web/src/main/webapp ~/shiva/hillview/web
Running webpack command in src/main/webapp
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by SivaMaplelabs** [comment]
After installing npm packages

root@hillview-root:~/shiva/hillview/bin# ./rebuild.sh
~/shiva/hillview/web ~/shiva/hillview/bin
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ web ---
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (Webpack bundle generation) @ web ---
~/shiva/hillview/web/src/main/webapp ~/shiva/hillview/web
Running webpack command in src/main/webapp
/root/shiva/hillview/web/src/main/webapp/node_modules/hard-source-webpack-plugin/index.js:105
  );
  ^

SyntaxError: Unexpected token )
    at NativeCompileCache._moduleCompile (/root/shiva/hillview/web/src/main/webapp/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/root/shiva/hillview/web/src/main/webapp/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:586:10)

**Comment by mbudiu-vmw** [comment]
Did you install all dependencies?

**Comment by mbudiu-vmw** [comment]
Can you check that you have a recent version of node-js?
This is the issue that you are hitting: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/380
On my machine, in hillview/web:
```
node --version
v11.4.0
```

**Comment by mbudiu-vmw** [comment]
This should be installed when you run ./bin/install-dependencies.sh, at least for Linux.
If you have a Mac we'll have to figure out how to use node.js 11.

**Comment by SivaMaplelabs** [comment]
root@hillview-root:~/DEPLOY-HILLVIEW/hillview# node -v
v6.14.4

Looks like the issue with the old version of node-js.
After upgrading to latest version, able to build the web project.
