### ISSUE TITLE
Extract value from a selection

### ISSUE THREAD

**Issue by amytai** [vmware/hillview#522]
Does not work - it produces a column with the wrong size.

**Comment by amytai** [comment]
Repro details:
1) Load the sample data at /home/hillview/data/syslog/syslog*
2) Do a filter, such as filtering by a string on the `Message` column
3) Plot the resulting column against time as a heatmap, then zoom into some subset of the heatmap
4) Convert the subset into a table (`View`-> `Table`)
5) Try to extract a value from a column in the generated table, such as extracting `tid` from the `StructuredData` column

This generates the following stacktrace:
```
48501296-fd49-45af-be8d-bb981bb3ef2e.kvCreateColumn()
java.lang.Exception: java.lang.IllegalArgumentException: Columns Host and tid do not have the same size
	at org.hillview.dataset.LocalDataSet.lambda$map$0(LocalDataSet.java:99)
Caused by: java.lang.IllegalArgumentException: Columns Host and tid do not have the same size
	at org.hillview.table.BaseTable.columnSize(BaseTable.java:111)
	at org.hillview.table.BaseTable.<init>(BaseTable.java:49)
	at org.hillview.table.Table.<init>(Table.java:87)
	at org.hillview.table.Table.replace(Table.java:143)
	at org.hillview.table.BaseTable.insertColumn(BaseTable.java:184)
	at org.hillview.maps.AppendColumnMap.apply(AppendColumnMap.java:58)
	at org.hillview.maps.AppendColumnMap.apply(AppendColumnMap.java:30)
	at org.hillview.dataset.LocalDataSet.lambda$map$0(LocalDataSet.java:94)
```
