### ISSUE TITLE
Failed to deploy Hillview on a cluter when using Aggregators

### ISSUE THREAD

**Issue by daniarherikurniawan** [vmware/hillview#647]
I will divide the problem into three sections, correspond to the order of my attempts.

**1.   I tried to deploy Hillview with 2 aggregators**
Failed when executing **./deploy.py config.json**  due to this error:
```
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [sender=2.6.9]
```

The script tried to rsync some files to a non-existing folder. In my case, there is no /home/hillview folder at the second aggregator, but the script tried to copy some scripts to that folder. Perhaps, the issue is about the order of the script. Before it rsync some files to the second aggregator, the script should complete the aggregator-preparation phase on that aggregator. I saw that the script successfully prepared the first aggregator, but it doesn’t do the same preparation to the second aggregator

**2   I tried to deploy Hillview with 1 aggregator**
Successfully execute deploy.py, but then I got this error when running **./start.py config.json**:
```
2020-07-21 11:45:44,752 - hillviewCommon - INFO - Reading cluster configuration from config.json
2020-07-21 11:45:44,752 - start - INFO - Starting web server cass-1.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 11:45:44,753 - hillviewCommon - INFO - On cass-1.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-webserver-manager.sh start
Tomcat started.
2020-07-21 11:45:45,938 - start - INFO - Starting aggregator cass-1.Cassandra-MitMem.cs331-uc.emulab.net
Traceback (most recent call last):
  File "./start.py", line 47, in <module>
    main()
  File "./start.py", line 43, in main
    config.run_on_all_aggregators(lambda rh: start_aggregator(config, rh))
  File "/Users/daniar/Documents/GitPR/hillview/bin/hillviewCommon.py", line 214, in run_on_all_aggregators
    function(rh)
  File "./start.py", line 43, in <lambda>
    config.run_on_all_aggregators(lambda rh: start_aggregator(config, rh))
  File "./start.py", line 34, in start_aggregator
    rh.run_remote_shell_command(config.service_folder + "/hillview-aggregator-manager.sh start")
NameError: name 'rh' is not defined 
```

This problem is related to the script that is generated on the remote server. Perhaps there is a bug on the generator.

 **3   I tried without any aggregator**
Successfully execute deploy.py and start.py, the status.py seems okay:
```
2020-07-21 13:15:58,350 - hillviewCommon - INFO - Reading cluster configuration from config.json
2020-07-21 13:15:58,352 - status - INFO - Checking hillview status on cass-1.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:15:58,353 - hillviewCommon - INFO - On cass-1.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-webserver-manager.sh status
18359
Web server running
2020-07-21 13:15:59,489 - status - INFO - Checking hillview status on cass-1.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:15:59,490 - hillviewCommon - INFO - On cass-1.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-worker-manager.sh status
Process seems to be running
2020-07-21 13:16:00,566 - status - INFO - Checking hillview status on cass-2.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:16:00,567 - hillviewCommon - INFO - On cass-2.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-worker-manager.sh status
Process seems to be running
2020-07-21 13:16:01,684 - status - INFO - Checking hillview status on cass-3.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:16:01,685 - hillviewCommon - INFO - On cass-3.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-worker-manager.sh status
Process seems to be running
2020-07-21 13:16:02,808 - status - INFO - Checking hillview status on cass-4.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:16:02,809 - hillviewCommon - INFO - On cass-4.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-worker-manager.sh status
Process seems to be running
2020-07-21 13:16:03,936 - status - INFO - Checking hillview status on cass-5.Cassandra-MitMem.cs331-uc.emulab.net
2020-07-21 13:16:03,937 - hillviewCommon - INFO - On cass-5.Cassandra-MitMem.cs331-uc.emulab.net: /home/hillview/hillview-worker-manager.sh status
Process seems to be running
```

However, http://cass-1.cassandra-mitmem.cs331-uc.emulab.net:8080/ is unreachable. I tried to do open that page from the remote machine and still got 404. 
```
daniar@cass-1:/mnt/extra $ wget http://cass-1.cassandra-mitmem.cs331-uc.emulab.net:8080/
--2020-07-21 12:36:47--  http://cass-1.cassandra-mitmem.cs331-uc.emulab.net:8080/
Resolving cass-1.cassandra-mitmem.cs331-uc.emulab.net (cass-1.cassandra-mitmem.cs331-uc.emulab.net)... 155.98.36.48
Connecting to cass-1.cassandra-mitmem.cs331-uc.emulab.net (cass-1.cassandra-mitmem.cs331-uc.emulab.net)|155.98.36.48|:8080... connected.
HTTP request sent, awaiting response... 404
2020-07-21 12:36:47 ERROR 404: (no description).

daniar@cass-1:/mnt/extra $ wget http://localhost:8080/
--2020-07-21 12:37:12--  http://localhost:8080/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 404
2020-07-21 12:37:12 ERROR 404: (no description).
```

I am still investigating this problem, perhaps because of my remote server, but I doubt it since I was able to run apache web server a few weeks ago. I  will post an update if I found any solution.

Side notes: This server is a testbed server, running on Linux. The installation that I did was java, Cassandra, and Hillview.  
Please let me know if you need more info. Thanks.

**Comment by lalithsuresh** [comment]
Step 3 not working is fishy. Can you look at the web server logs?

**Comment by daniarherikurniawan** [comment]
This is the  hillview.log
```
2020-07-21 12:14:52.622,none,INFO,cass-1.cassandra-mitmem.cs331-uc.emulab.net,main,org.hillview.utils.HillviewLogger,<init>,Starting logger,Working directory: /home/hillview/.
2020-07-21 12:14:52.639,worker,INFO,cass-1.cassandra-mitmem.cs331-uc.emulab.net,main,org.hillview.utils.ExecutorUtils,getComputeExecutorService,Detect CPUs,Using 32 processors
2020-07-21 12:14:52.940,worker,INFO,cass-1.cassandra-mitmem.cs331-uc.emulab.net,main,org.hillview.utils.HillviewLogger,info,Created HillviewServer,
```

hillview-web.log
```
2020-07-21 12:14:52.821,none,INFO,cass-1.cassandra-mitmem.cs331-uc.emulab.net,main,org.hillview.utils.HillviewLogger,<init>,Starting logger,Working directory: /home/hillview/.
2020-07-21 12:14:52.822,web server,INFO,cass-1.cassandra-mitmem.cs331-uc.emulab.net,main,org.hillview.utils.HillviewLogger,info,Server started,
```

I attached my cluster config.json

[cluster-config.txt](https://github.com/vmware/hillview/files/4972818/cluster-config.txt)

**Comment by daniarherikurniawan** [comment]
You can access the content of the first worker here http://cass-1.cassandra-mitmem.cs331-uc.emulab.net/CASS-1/

**Comment by lalithsuresh** [comment]
Are there iptables rules or some kind of firewall affecting connectivity between machines?

The logs aren't very useful in this state, you'd need to bump up the log-level.

@mbudiu-vmw can confirm, but I think Tomcat should have logs of its own that you can inspect.

**Comment by daniarherikurniawan** [comment]
I believe there is no firewall affecting the cluster connections. The server can ping each other without a problem, and my cassandra cluster is still running normally on this cluster.

**Comment by lalithsuresh** [comment]
Can you try manually running `bin/backend-start.sh` and `bin/frontend-start.sh` as the README suggests, and see if the web-server is accessible from localhost?

**Comment by daniarherikurniawan** [comment]
Yes, I can confirm that it can run standalone (single node) mode normally. You can visit http://cass-1.cassandra-mitmem.cs331-uc.emulab.net:8080. I installed it manually after cloning the GitHub. 

I noticed that some scripts don't work. I ended up running the script per line to figure out which line caused the error. For instance, some scripts may ask for a confirmation input (like 'y' or 'A'), there will be a problem if we place that script within a subfile. The shaded Cassandra must be installed locally with a special command, not just mvn install. The other is about install-dependencies.sh failed to read tomcat version from lib.sh. 

And also my ~/ folder has limited space and the mvn failed due to disk limit exceeded. So, I need to change the default local repo as well. If you might want to take a look, I attached the full script that works on my ubuntu servers, but it must be run manually (copy-paste). The script will install Hillview at /mnt/extra, tested at 4 different ubuntu servers. 

[script-ubuntu.txt](https://github.com/vmware/hillview/files/4974813/script-ubuntu.txt)

**Comment by mbudiu-vmw** [comment]
There was a trivial typo in a python program, which I fixed.
Perhaps @daniarherikurniawan can test the new result.
github has automatically closed this issue when I merged the commit, please reopen if it's not fixed.

**Comment by daniarherikurniawan** [comment]
Confirmed! I can deploy Hillview on my Linux cluster. Thanks!
